### ISSUE TITLE
Allied: skale.js esm exports are needed for seemless integration

### ISSUE THREAD

**Issue by adiled** [skalenetwork/admin-ui#15]
- [ ] bundling without quirks through esbuild
- [ ] bundling without quirks through rollup

**Comment by TheGreatAxios** [comment]
Planned Fix in https://github.com/Dirt-Road-Development/skale.js/issues/69

**Comment by TheGreatAxios** [comment]
@adiled https://github.com/Dirt-Road-Development/skale.js/issues/69 this was completed with most recent builds, can you please confirm if this solves the issue with the call on your end?

**Comment by adiled** [comment]
@TheGreatAxios I'll check.

**Comment by adiled** [comment]
minimum required: polyfilling `assert`
