### ISSUE TITLE
Multisig + Marionette: Deep Dive

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/admin-ui#16]
Overview
---
Due to the default permissions and pre-deployed contracts on each SKALE chain, the setup is nearly always the same [minus a few staging/testnet chains]. This setup includes the usage of a dual multi-signature wallet system.

This system utilizes by default the https://github.com/skalenetwork/multisigwallet-predeployed deployed on the SKALE Chain. Additionally, a Gnosis SAFE (multi-signature wallet/contract) on the Ethereum Mainnet is also used. 

However, while the mainnet SAFE is a SKALE Chain owner, technically, the multisig on chain is not, and is simply the primary signer on Marionette, which is technically the on-chain SKALE Chain Owner.

This presents an interesting routing situation for transactions to succeed by default. 

A **basic** path for transacting could be an Externally Owned Account (EOA) to a smart contract i.e 0xABC..123 calls transfer() on ERC-20. 

A **complex** path for transacting could be an Externally Owned Account (EOA) to a Gnosis SAFE i.e 0xABC..123 calls (execTransaction)[https://github.com/safe-global/safe-contracts/blob/06c35bd4200fa9a2929e498cafe61c57c7e9970e/contracts/Safe.sol#L135] on Gnosis SAFE where the function called through the SAFE is the same ERC-20 token transfer as above. 

Individuals use multi-signature wallets for many reasons, currently, the usage of these multi-signature wallets on SKALE results in the need for transactions to [usually] be sent in a more complex path than a basic path. 

The current setup of how the two multi-signature wallets link to Marionette can be seen here:

![image](https://user-images.githubusercontent.com/20197130/223514714-d775a21c-b8ba-42bf-b09a-a9e3740cf557.png)

What this represents is that the default for a SKALE Chain owner who has a branch new chain is that they MUST utilize a multi-signature wallet to access the chain, as their Backup will not have any roles. The multi-signature wallet on the SKALE Chain side won't even have some of the more commonly used roles. 

The only role that these two multi-signature wallets have on the SKALE Chain side is PUPPETEER_ROLE on Marionette which in turn is the DEFAULT owner for ALL pre-deployed contracts including IMA.

Expected Outcome
---

1. Simplest Route - The UI should understand that a user may have elevated roles for one contract and not another. Preference should always be to send transactions directly via the EOA. However, if permissions are unavailable then the functionality would automatically be routed through Multisg + Marionette [not just Multisig]. 

2. Understanding of Gas Limit. Due to the routing of the Multisig + Marionette above; should plan in advance to manually raise/multiply gas limits to avoid failure somewhere in the multisig <--> Marionette stages which can cause headache for developers.

**Comment by TheGreatAxios** [comment]
@adiled 

Following up on the above, 

1. Please disable/hide M2S IMA for ERC-20, ERC-721, and ERC-1155 for now due to increased requirements for usage with the Gnosis SAFE. 
2. Note on Admin UI thoughts on Multisig + marionette, this is a bit of a follow-up thought process so I can spell it out. 
I am worried that this is going to be too potentially too confusing but this is technically the flow if I am not mistaken since if you have multiple signers you cannot send directly through msg + marionette. Only the last signer can successfully make that call. 

SKALE Chain to SKALE Chain (S2S) can proceed as follows, the only difference is that transactions should be sent through the pre-deployed multisig + marionette **IF** the Externally Owned Account sending transactions has no roles. Additionally, when transactions are fired in this manner most pre-deployed multisig wallets at some point will have more than 1 signer and more than 1 confirmation; however, during the initial chain setup this may vary and chain owners will generally lean on a single signer to setup a chain which is when the Admin UI will be most useful. 

In order to manage single confirmation vs multi-confirmation when using Multisig + Marionette; the following should be done before sending transactions. 

1. Check for requirements on Pre-deployed Multi-signature wallet. 
2. If requirements == 1, send transaction via multisig + marionette
3. else (requirements > 1) create transaction in multisig wallet / use existing multisig wallet transaction [and be the final signer]


This flow would enable a project to have multiple signers manage transactions and the final signature would result in sending it through marionette.

**Comment by adiled** [comment]
@TheGreatAxios Thank you, that's very insightful. I'll be introducing these changes from https://github.com/skalenetwork/admin-ui/tree/next
