### ISSUE TITLE
Node script for compiling chains Error

### ISSUE THREAD

**Issue by SKALE-jace** [skalenetwork/admin-ui#33]
Steps to Reproduce:

- git clone repo && `cd`
- set to node v18.16.0
- run `yarn install`
- run `yarn compile:chains` 
  - alias of `npx ts-node --project ./scripts/tsconfig.scripts.json --transpileOnly ./scripts/compile-chains.ts`

**Returns error:**
![CleanShot 2023-05-23 at 16 36 56@2x](https://github.com/skalenetwork/admin-ui/assets/103141574/b45c4861-d610-4bef-92a3-e565e7e46f4c)

## How I got my local working:

`yarn add  tsx@3.12.7`
`npx tsx ./scripts/compile-chains.ts`

![CleanShot 2023-05-23 at 16 38 23@2x](https://github.com/skalenetwork/admin-ui/assets/103141574/9a83025f-be53-49bb-a51f-ef104bb5fc1c)

**Comment by adiled** [comment]
@SKALE-jace, I was just facing this again in monorepo setup too which is to be merged today. Thanks a lot for `tsx` suggestion, I'll try the replacement!

**Comment by adiled** [comment]
Resolve with `tsx` in #32
